language: go

sudo: false

go:
- 1.9

cache:
  directories:
  - $HOME/local

before_install:
- go get github.com/golang/dep/cmd/dep

install:
- dep ensure

script:
- make test

env:
  global:
  - "PATH=$PATH:$HOME/local/bin"

notifications:
  email: false

